import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'

import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

import Header from '@/components/Header'
import Dashboard from '@/components/Dashboard'
import TodoList from '@/components/TodoList'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  let [selectedName, setSelectedName] = useState("No item selected")
  let [selectedTag, setSelectedTag] = useState("No item selected")
  let [selectedId, setSelectedId] = useState(-1);

  const selectItem = (name: string, tag: string, id: number) => {
    setSelectedName(name);
    setSelectedTag(tag);
    setSelectedId(id);
  }

  let [totalTasks, setTotalTasks] = useState(0);

  const countTotalTasks = (items: {}[]) => {
    setTotalTasks(items.length);
  }

  let [countChecked, setCountChecked] = useState(0);

  const handleCheckChange = (item: {}) => {
    if (item.checked) {
      item.checked = false;
      setCountChecked(countChecked - 1);
    } else {
      item.checked = true;
      setCountChecked(countChecked + 1);
    }
    console.log(item.checked);
  }

  let [ bgImage, setBgImage ] = useState("url('#')");

  const handleBgImageChange = (imageUrl: string) => {
    setBgImage(imageUrl);
  }

  return (
    <>
      <Head>
        <title>Thắm&apos;s Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-image' style={{ backgroundImage: bgImage }}>
        <div className='container w-50 pt-4 pb-5'>
          <Header handleBgImageChange={handleBgImageChange} />
          <Dashboard selectedName={selectedName} selectedTag={selectedTag} totalTasks={totalTasks} completedTasks={countChecked}/>
          <TodoList handleSelect={selectItem} selectedId={selectedId} countTotal={countTotalTasks} handleCheckChange={handleCheckChange}/>
        </div>
      </main>
    </>
  )
}
